### PR TITLE
Fixing build bugs with newer oiio version

### PR DESCRIPTION
**Pull request by marza-sergey**
When trying to build with OpenImageIO 2.4.11 I was getting the following errors:
`This version of OIIO is meant to work only with C++14 and above`
and
```
/opt/rh/gcc-toolset-11/root/usr/bin/c++ -O3 -DNDEBUG -rdynamic CMakeFiles/MaterialXView.dir/Editor.cpp.o CMakeFiles/MaterialXView.dir/Main.cpp.o CMakeFiles/MaterialXView.dir/RenderPipelineGL.cpp.o CMakeFiles/MaterialXView.dir/Viewer.cpp.o -o ../../bin/MaterialXView  -Wl,-rpath,/src/release/lib64::::::::::::::::::::: ../../lib/libMaterialXFormat.a ../../lib/libMaterialXGenGlsl.a ../../lib/libMaterialXRender.a ../../lib/libMaterialXRenderGlsl.a ../../lib/libMaterialXGenOsl.a ../../lib/libMaterialXGenMdl.a ../../lib/libnanogui.a ../../lib/libMaterialXGenGlsl.a ../../lib/libMaterialXRenderHw.a ../../lib/libMaterialXRender.a /src/release/lib64/libOpenImageIO.so -lOpenGL -lGLX -lGLU -lSM -lICE -lX11 -lXext -lXt ../../lib/libMaterialXGenShader.a ../../lib/libMaterialXFormat.a ../../lib/libMaterialXCore.a -lX11 -lpthread -lGL -lrt -ldl 
/opt/rh/gcc-toolset-11/root/usr/bin/ld: ../../lib/libMaterialXRender.a(OiioImageLoader.cpp.o): undefined reference to symbol '_ZN16OpenImageIO_v2_410ParamValue12init_noclearENS_7ustringENS_8TypeDescEiNS0_6InterpEPKvNS0_4CopyENS0_11FromUstringE'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: /src/release/lib64/libOpenImageIO_Util.so.2.4: error adding symbols: DSO missing from command line
```

### CODE REVIEW

**Comment by jstone-lucasfilm** [comment]
Thanks for this post, @marza-sergey!  Let us know if you run into any issues with the CLA process for the MaterialX project, and the Linux Foundation is usually very responsive if you fill out a support ticket using the link above.

**Comment by marza-sergey** [comment]
@jstone-lucasfilm No problem, I'm just waiting for a response from someone at the company to sign agreement and appoint CLA manager.

**Comment by marza-sergey** [comment]
Unfortunately it's not a technical problem and this PR became a part of larger internal discussions about managing open source from legal point of view.  I was told that we will resolve this issue soon, but without any specific dates. Sorry, for inconvenience.

**Comment by jstone-lucasfilm** [comment]
Thanks for getting this conversation started, @marza-sergey, and I'll close out this proposal so that we can focus our discussion on the latest proposal in #1488.
